### ISSUE TITLE
ERROR: for rothenberg_nginx-proxy_1 : Cannot start service nginx-proxy

### ISSUE THREAD

**Issue by jorismulliez** [norsys/rothenberg#20]
Hi,

I want to test this tools, but I've got some errors on fresh install.
I'm completely new to docker ecosystem...

Thanks for your help

First : 
```
Status: Downloaded newer image for jwilder/nginx-proxy:0.4.0
Creating rothenberg_nginx-proxy_1 ... error

ERROR: for rothenberg_nginx-proxy_1  Cannot start service nginx-proxy: driver failed programming external connectivity on endpoint rothenberg_nginx-proxy_1 (170b4449ceb44c8ec61e3f2d281da85871bf98a567966a0657580d78fa4247ee): Error starting userland proxy: listen tcp 0.0.0.0:80: listen: address already in use

ERROR: for nginx-proxy  Cannot start service nginx-proxy: driver failed programming external connectivity on endpoint rothenberg_nginx-proxy_1 (170b4449ceb44c8ec61e3f2d281da85871bf98a567966a0657580d78fa4247ee): Error starting userland proxy: listen tcp 0.0.0.0:80: listen: address already in use
ERROR: Encountered errors while bringing up the project.
```
And later : 
```
Status: Downloaded newer image for nginx:1.13.3
Creating network "testdockerdev_default" with the default driver

Fatal error: Uncaught Symfony\Component\Debug\Exception\FatalThrowableError: Type error: Return value of Doctrine\Common\Annotations\AnnotationRegistry::registerFile() must be an instance of Doctrine\Common\Annotations\void, none returned in /src/vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/AnnotationRegistry.php:67
Stack trace:
#0 /src/vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/AnnotationReader.php(200): Doctrine\Common\Annotations\AnnotationRegistry::registerFile('/src/vendor/doc...')
#1 /src/var/cache/dev/ContainerT6wvsaq/appDevDebugProjectContainer.php(666): Doctrine\Common\Annotations\AnnotationReader->__construct()
#2 /src/var/cache/dev/ContainerT6wvsaq/getAnnotations_CacheWarmerService.php(8): ContainerT6wvsaq\appDevDebugProjectContainer->getAnnotations_ReaderService()
#3 /src/var/cache/dev/ContainerT6wvsaq/appDevDebugProjectContainer.php(442): require('/src/var/cache/...')
#4 /src/var/cache/dev/ContainerT6wvsaq/getCacheWarmerService.php(13): ContainerT6wvsaq\appDevDebugProjectContai in /src/vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/AnnotationRegistry.php on line 67
make: *** [web/bundles] Erreur 255
``` 

The steps before this error : 
```
mkdir test_rothenberg;
cd test_rothenberg;
wget -O - https://github.com/norsys/rothenberg/raw/master/install.sh | sh;
make start;
```
Here are my versions : 

> Docker version 17.12.0-ce, build c97c6d6
> docker-compose version 1.18.0, build 8dd22a9
> GNU Make 3.81

And docker infos : 
```
$ docker ps -a
CONTAINER ID        IMAGE                       COMMAND                  CREATED             STATUS              PORTS               NAMES
672593628a79        jwilder/nginx-proxy:0.4.0   "/app/docker-entrypo…"   21 minutes ago      Created                                 rothenberg_nginx-proxy_1
```
```
$ docker network ls
NETWORK ID          NAME                        DRIVER              SCOPE
0fe48989f094        bridge                      bridge              local
47f432248581        dockersymfony_default       bridge              local
12a98a445d3d        testdockerdev_default       bridge              local
d88df917013a        host                        host                local
622aa65f34af        none                        null                local
4b825dd47947        rothenberg_default          bridge              local
```

And here is my "make start" with debug : 
```
$ make start WITH_DEBUG=yes
env/common.mk:55: 
+ uname -s
env/Makefile:12: 
+ bin/docker-compose -f env/docker-compose.rothenberg.yml -p rothenberg up -d
Creating network "rothenberg_default" with the default driver
Creating rothenberg_nginx-proxy_1 ... error

ERROR: for rothenberg_nginx-proxy_1  Cannot start service nginx-proxy: driver failed programming external connectivity on endpoint rothenberg_nginx-proxy_1 (17a530d5ad9b802865a4f3c618f97aa943240889361ed46eb107111ca7083bb7): Error starting userland proxy: listen tcp 0.0.0.0:80: listen: address already in use

ERROR: for nginx-proxy  Cannot start service nginx-proxy: driver failed programming external connectivity on endpoint rothenberg_nginx-proxy_1 (17a530d5ad9b802865a4f3c618f97aa943240889361ed46eb107111ca7083bb7): Error starting userland proxy: listen tcp 0.0.0.0:80: listen: address already in use
ERROR: Encountered errors while bringing up the project.
+ true
env/Makefile:37:  Update target web/bundles
env/common.mk:52:  Update target web/bundles
+ id -u
env/common.mk:45:  Update target web/bundles
+ which docker
+ bin/console assets:install
Creating network "testdockerdev_default" with the default driver

 Installing assets as hard copies.

                                                                                
 [OK] No assets were provided by any bundle.                                    
                                                                                

env/common.mk:124:  Update target docker/pull
env/common.mk:52:  Update target docker/pull
+ id -u
env/common.mk:45:  Update target docker/pull
+ which docker
env/common.mk:124:  Update target docker/pull
+ bin/docker-compose pull --ignore-pull-failures
Pulling node (node:7.10.1)...
7.10.1: Pulling from library/node
Digest: sha256:af5c2c6ac8bc3fa372ac031ef60c45a285eeba7bce9ee9ed66dad3a01e29ab8d
Status: Image is up to date for node:7.10.1
Pulling composer (composer:1.4.2)...
1.4.2: Pulling from library/composer
Digest: sha256:b497d9c8154d9a175fbf2b0293989b4c650daf8950e34a019d7c44188d8205b3
Status: Image is up to date for composer:1.4.2
Pulling phantomjs (wernight/phantomjs:2.1.1)...
2.1.1: Pulling from wernight/phantomjs
03e1855d4f31: Already exists
a3ed95caeb02: Already exists
574e9188e52e: Already exists
933a9a2acc6d: Already exists
fd24a64ca53d: Already exists
Digest: sha256:5621d6496585af78908251451eb647b45a7f6f45a9c3181a231a99e1bb2ec264
Status: Image is up to date for wernight/phantomjs:2.1.1
Pulling hosts (ubuntu:16.04)...
16.04: Pulling from library/ubuntu
Digest: sha256:e27e9d7f7f28d67aa9e2d7540bdc2b33254b452ee8e60f388875e5b7d9b2b696
Status: Image is up to date for ubuntu:16.04
Pulling php-cli (php:7.0-cli)...
7.0-cli: Pulling from library/php
Digest: sha256:3084a4923529fa87a7f523d6979a964d2a24b166ab973dc138da6e4aeceda2a8
Status: Image is up to date for php:7.0-cli
Pulling mysql (mysql:5.6.31)...
5.6.31: Pulling from library/mysql
Digest: sha256:1d99ad1a8a2f8859dc986566cc31741c00a050d5fbf9305e7cd74398ade79f36
Status: Image is up to date for mysql:5.6.31
Pulling php-fpm (php:7.0-fpm)...
7.0-fpm: Pulling from library/php
Digest: sha256:28ac367e65b1fa3588a28a2f71f95f49064834b74459aef6921084f03e51e935
Status: Image is up to date for php:7.0-fpm
Pulling nginx (nginx:1.13.3)...
1.13.3: Pulling from library/nginx
Digest: sha256:788fa27763db6d69ad3444e8ba72f947df9e7e163bad7c1f5614f8fd27a311c3
Status: Image is up to date for nginx:1.13.3
env/Makefile:26:  Update target install/host
env/common.mk:52:  Update target install/host
+ id -u
env/common.mk:45:  Update target install/host
+ which docker
+ bin/docker-compose run --rm hosts bash -c grep -q -F '127.0.0.1 test-docker.dev' /tmp/etc/hosts || echo '127.0.0.1 test-docker.dev' >> /tmp/etc/hosts
env/common.mk:117:  Update target docker/clean
+ which docker
env/common.mk:117:  Update target docker/clean
env/common.mk:52:  Update target docker/clean
+ id -u
env/common.mk:45:  Update target docker/clean
+ which docker
+ /usr/bin/docker system prune -f
Deleted Containers:
98146cdd981693a5c3d7db3a54121843bded71c73dc74f9842609779097c0e5f

Deleted Networks:
rothenberg_default
testdockerdev_default

Total reclaimed space: 0B
env/Makefile:19:  Update target install from docker/pull due to docker/pull node .install install/host docker/clean .git/hooks/pre-commit
env/common.mk:52:  Update target install from docker/pull due to docker/pull node .install install/host docker/clean .git/hooks/pre-commit
+ id -u
env/common.mk:45:  Update target install from docker/pull due to docker/pull node .install install/host docker/clean .git/hooks/pre-commit
+ which docker
+ cat .install
+ sed -e s/:[^#]*##/?=/ -e s/\(.*\)?=/\\033[92m\1\\033[0m:/
+ column -c2 -t -s :
+ printf \033[92mENV \033[0m           dev
\033[92mSYMFONY_ENV \033[0m   dev
\033[92mSSH_KEY \033[0m       /home/me/.ssh/id_rsa\n
ENV            dev
SYMFONY_ENV    dev
SSH_KEY        /home/me/.ssh/id_rsa
env/Makefile:96:  Update target nginx from bin/docker-compose due to bin/docker-compose
env/common.mk:52:  Update target nginx from bin/docker-compose due to bin/docker-compose
+ id -u
env/common.mk:45:  Update target nginx from bin/docker-compose due to bin/docker-compose
+ which docker
+ bin/docker-compose up -d nginx
Creating network "testdockerdev_default" with the default driver
ERROR: Network rothenberg_default declared as external, but could not be found. Please create the network manually using `docker network create rothenberg_default` and try again.
make: *** [nginx] Erreur 1
```

Thanks,

**Comment by mageekguy** [comment]
Hi!
Firstly, thanks to try to use atoum!
Secondly, i think that you already have a service which listen on `0.0.0.0:80` on your computer.
So, rothenberg can't set up the ngninx proxy on this IP, and you must stop the current running service on this IP and this port before `make start`.
To know the process which listen on `0.0.0.0:80`, execute `sudo netstat -taupen | grep 0.0.0.0` in a terminal.
Don't hesitate to give us any feedback!

**Comment by mageekguy** [comment]
No feedback? Can i close this issue?

**Comment by jorismulliez** [comment]
Hi @mageekguy ,

I'm sorry, I didn't follow up on this test.
You can close (or remove) this issue.

Thanks,
